# Generated by Django 3.0.7 on 2020-06-06 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_id', models.PositiveIntegerField(db_index=True)),
                ('image', models.ImageField(blank=True, upload_to='store_pics/')),
                ('title', models.CharField(max_length=50)),
                ('slogan', models.CharField(max_length=250)),
                ('about', models.TextField()),
                ('rate', models.PositiveIntegerField()),
                ('address', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('followers', models.ManyToManyField(blank=True, related_name='stores_followed', to=settings.AUTH_USER_MODEL)),
                ('owner_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='own_store', to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='shops.Store')),
            ],
        ),
    ]
