# Generated by Django 3.0.7 on 2020-06-17 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='font_image',
            field=models.ImageField(default='default.jpg', upload_to='font_images/'),
        ),
    ]
