# Generated by Django 3.0.7 on 2020-06-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200617_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='font_image',
            field=models.ImageField(default='font_images/default.jpg', upload_to='font_images/'),
        ),
    ]
