# Generated by Django 3.0.7 on 2020-06-18 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200617_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='font_image',
            field=models.ImageField(upload_to='font_images/'),
        ),
    ]
