# Generated by Django 3.0.7 on 2020-07-06 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-date_uploaded',)},
        ),
    ]
