# Generated by Django 3.0.7 on 2020-06-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_super_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_super_user',
            new_name='is_superuser',
        ),
    ]
